version: "3"

services:
  mariadb:
      container_name: mariadb
      env_file:
        - .env
      build: ./requirements/mariadb
      image: mariadb:inception
      restart: always
      volumes:
        - db_volume:/var/lib/mysql
      networks:
        - inception
      stdin_open: true

  wordpress:
      container_name: wordpress
      env_file:
        - .env
      build: ./requirements/wordpress
      image: wordpress:inception
      restart: always
      depends_on:
        - mariadb
      volumes:
        - wp_volume:/var/www/html
      networks:
        - inception

  nginx:
      container_name: nginx
      env_file:
        - .env
      ports:
        - 443:443  # Maps port 443 on the host to port 443 on the container
        # The purpose of mapping port 443 on the host to port 443 on the Nginx container is to allow 
        # incoming HTTPS traffic to reach the Nginx container, which then forwards 
        # the requests to Wordpress
      build: ./requirements/nginx
      image: nginx:inception
      restart: always
      depends_on:
        - wordpress
      volumes:
        - wp_volume:/var/www/html
      networks:
        - inception

networks:
  inception:
    driver: bridge

volumes:
  db_volume:
    driver: local
    driver_opts:
      type: bind
      o: none
      device: /Users/aoumad/Desktop/inception/mariadb
  wp_volume:
    driver: local
    driver_opts:
      type: bind
      o: none
      device: /Users/aoumad/Desktop/inception/wordpress